version: "3.8"
services:
    postgres-nest:
        image: postgres:15.4
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - DB_NAME=postgres-nest
        ports:
            - 5432:5432
        networks:
            - shared-network
        volumes: 
            - ./postgres-db:/var/lib/postgres/data

    backend:
        container_name: backend
        restart: unless-stopped
        image: backend-prod:1.0.0
        build:
            context: backend
            target: production
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - shared-network



networks:
    shared-network: